### PR TITLE
feat: run Glee in container, edit Glee local

### LINKED ISSUE #735: [FEATURE] Run Glee in a container
### Why do we need this improvement?

Setting/maintaining a fully functional node environment on local machine can be overwhelming and hard to debug. A container is much easier to deploy/manage

### How will this change help?

The prerequisite effort to install Docker or equivalent is shared over many projects. 
On download of the compose.yaml a simple "docker compose up" launches the Glee server with default settings. From there you can modify the Glee files and stop/restart the Glee server to explore all features of Glee

No need to worry about install of node, .gyp, python etc

### Screenshots

_No response_

### How could it be implemented/designed?

A (docker) compose.yaml that pulls asyncapi/cli image, runs new glee, npm install, npm run dev commands and attaches to local filesystem. 

A refinement of below yaml

- get away from USER root
- .gyp and python to be included in cli image
- improve naming of directory in local file system
- smart permissions on directory in local file system
- documentation on usage

```
version: '3'

services:
  glee:
    build:
      context: .
      dockerfile_inline: |
        FROM asyncapi/cli
        USER root
        RUN apk add --no-cache --virtual .gyp python3 make g++ && \
            rm -rf /var/lib/apt/lists/* && \
            asyncapi new glee && \
            cd project && \
            npm install
        ENTRYPOINT 
    volumes:
      - ${PWD}/output:/app 
    networks:
      - default
    user: root
    entrypoint: []
    working_dir: /app/project
    command: npm run dev
    
networks:
  default: {}
```

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by eelcofolkertsma**
**Description**
Setting/maintaining a fully functional node environment on local machine can be overwhelming and hard to debug. A container is much easier to deploy/manage

*How will this change help?*
The prerequisite effort to install Docker or equivalent is shared over many projects.
On download of the compose.yaml a simple "docker compose up" launches the Glee server with default settings. From there you can modify the Glee files and stop/restart the Glee server to explore all features of Glee

No need to worry about install of node, .gyp, python etc

**Related issue(s)**
Resolves #735

### CODE REVIEW

**Comment by eelcofolkertsma** [comment]
As described in enhancement issue:
develop a docker compose file for easy launch of glee server in container with Glee files exposed on local file system
The container assures Glee runs in well controlled environment (node, npm, python, .gyp etc)
Local exposure allows to use editor of personal preference

A usage file explains how to deploy a container, edit the glee files, and stop/restart Glee for new input. Usage assume almost zero docker knowledge and focuses on bare minimum to run the Glee server

**Comment by KhudaDad414** [comment]
@eelcofolkertsma please mark the PR as `Ready for Review` when it's ready. thanks. 🙇

**Comment by eelcofolkertsma** [comment]
# Current approach
- Docker-compose.yaml to launch persistent container with asyncapi/cli and shared folder between container and local file system
- Open command prompt in container (docker exec)
- Use standard asyncapi commands to create Glee tutorial project and initialize (Npm run) and start server (Npm run dev). Keep terminal connected for Glee log
- Switch to an editor that can modify Glee in local file system and tweak as desired. See at Glee log how server follows asyncapi.yaml and functions updates
- Send test messages and have fun

One can terminate/remove container with docker compose down command

One can "factory reset" the Glee files with forced new Glee

It is basic setup with lots of possible improvements. 

I shall wire stuff together over next week, including usage document. I shall also as for some feedback to decide if further evolution makes sense

**Comment by KhudaDad414** [comment]
@eelcofolkertsma are you still working on this?

**Comment by eelcofolkertsma** [comment]
> @eelcofolkertsma are you still working on this?

Yes, I am. Progress is slow, in part other priorities did have to go first, in part issue is more tough than I expected. 
But I am sure something will result and it will be reported under this topic

Thanks for asking ;-)

**Pull request closed without merging**
