### PR TITLE
feat: add support for multiple .env files.

### PR DESCRIPTION
**Pull request by AkhilJ321**
**Description**

- Added Support for multiple .env files.
- Added Documentation for the same.

**Related issue(s)**
Fixes: #638

### CODE REVIEW

**Review by KhudaDad414 — CHANGES_REQUESTED** [review]
@AkhilJ321 Please resolve the conflicts. btw, have you tested it?

**Comment by AkhilJ321** [comment]
@KhudaDad414  yes , I tested it through a example where npm run dev used development env and on npm run start used production env.

**Comment by AkhilJ321** [comment]
@KhudaDad414 ,I am not getting what to remove, I have only removed dotenv imports and added next/env. What confict is to be resolved ,can you help me with this one

**Comment by KhudaDad414** [comment]
@AkhilJ321 Conflicts happen when someone makes a change to a file that you are working on in your PR. because GitHub doesn't know which changes it should keep.

what conflict is: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts
how to resolve the conflict: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by AkhilJ321** [comment]
@KhudaDad414 Thank you for the help, resolved the conflict.

**Review by KhudaDad414 — APPROVED** [review]

**Comment by KhudaDad414** [comment]
thanks for the contribution @AkhilJ321 🙇

**Comment by KhudaDad414** [comment]
@allcontributors please add @AkhilJ321 for code

**Pull request merged**
