### PR TITLE
fix: fixed social network example

### LINKED ISSUE #239: Social network example is failing
#### Describe the bug
The example at `examples/social-network` is failing.

#### How to Reproduce
Try going to this folder, and running `npm run dev` on any of the Glee apps.

It fails because the `lowdb` package is an ES Module (those using `import` instead of `require`) and we're compiling all the Typescript code (except `node_modules`) to CommonJS modules (those using `require` instead of `import`). Therefore, it doesn't expect an `import` keyword and fails.

#### Expected behavior
It should support ES Modules out of the box. There will be more and more packages migrating to ES Modules over time as it's the new standard. ES modules can `import` CommonJS modules but CommonJS modules can't `require` ES Modules.

It should be easy to do. Initially, Glee supported them very well but after the Typescript migration (#212 and #213) it got broken. Changing all the code to ES Modules (and adding back `.js` extension to all `import`s) should be fine except for Jest mock of `fs/promises` in the `test/lib/functions.test.ts` file, which doesn't work yet with ESM.

I think a good and quick solution would be to just get rid of this test for now until Jest supports ESM. Check the progress (or even better, contribute) at https://github.com/facebook/jest/pull/10976.

### PR DESCRIPTION
**Pull request by sudoshreyansh**
**Description**

- Migrated to ESM Modules
- Disabled `functions.test.ts`
- Tested dynamic imports in windows and linux

**Related issue(s)**
Resolves #239

### CODE REVIEW

**Comment by fmvilas** [comment]
I found two issues:

### Examples not running

I'm getting this error while trying to run the websocket-server or any other example:

```
$ npm run dev

> websocket-server@0.1.0 dev /Users/fmvilas/www/glee/examples/social-network/websocket-server
> glee dev

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/fmvilas/www/glee/dist/lib/compiler' imported from /Users/fmvilas/www/glee/dist/cli/index.js
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Any hints? I cleared `node_modules`, removed `package-lock.json`, and reinstalled everything but nothing works :/

### Tests for `functions.ts` file

The tests included in `functions.test.ts` are not being executed when I run `npm test`. Any idea?

**Comment by fmvilas** [comment]
Forget about the `functions.test.ts` stuff. I just saw you're ignoring it on purpose 👍

**Comment by sudoshreyansh** [comment]
@fmvilas Maybe you didn't build glee itself?

**Comment by fmvilas** [comment]
You're right 🤦 Too many years using raw JS 😄

**Review by fmvilas — APPROVED** [review]
Great work, @sudoshreyansh 👏

**Pull request merged**
