### PR TITLE
refactor: removed duplicate import from src/index.js

### PR DESCRIPTION
**Pull request by joeljose350**
`startRuntimeServers` and `triggerFunction` were imported from `src/lib/runtimes/index.js` in 2 separate import statements. Issue #116 mentioned this problem and this pull request fixes that issue by importing both functions with 1 import statement.

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@joeljose350 Thanks for contribution! Please update description with changes along with reference to the issue and also please remove the number of pointed issue in the PR's title.

**Comment by joeljose350** [comment]
I have made the changes you requested @magicmatatjahu. I hope it's able to be merged now.

**Review by magicmatatjahu — APPROVED** [review]

**Comment by magicmatatjahu** [comment]
@joeljose350 Last thing. It's not fix, but only refactor - you don't change/fix code, but only make refactor, so please change prefix for PR's title to the refactor:

**Comment by magicmatatjahu** [comment]
@joeljose350 We have some problem with macos related workflows, but don't worry I will merge it immediately when all workflows will pass.

**Pull request merged**
