### PR TITLE
refactor: added Prettier on entire codebase

### LINKED ISSUE #398: add prettier configuration
#### Reason/Context
We currently use eslint for the linting purposes but linting can only get us so far.
We can enforce the code styling guidelines in our codebase by having a `prettier` config file to enforce the guidelines that are not covered by the linter. for example: rules regarding semi-colon usage or trailing commas.

#### Description
* Add a `.prettierrc` file to the codebase and try to fine tune it's settings the the current codebase style.
* Reformat the current codebase with prettier.

### PR DESCRIPTION
**Pull request by Queen-codes**
**Description**

- Run Prettier to format all code in the codebase
- Add .prettierrc configuration file to set code formatting options

**Related issue(s)**
- Fixes #398 
-
Screenshot 2023-03-14 at 18 06 04

### CODE REVIEW

**Review by KhudaDad414 — CHANGES_REQUESTED** [review]
@Queen-codes We are using node 18 for this project. can you please regenerate your package-lock.json with that version?

**Comment by Queen-codes** [comment]
> @Queen-codes We are using node 18 for this project. can you please regenerate your package-lock.json with that version?

alright, would do this. Thank you very much

**Comment by Queen-codes** [comment]
> @Queen-codes We are using node 18 for this project. can you please regenerate your package-lock.json with that version?

HI @KhudaDad414 . Already did this. Please kindly review and confirm if I need to make any changes again.

**Comment by KhudaDad414** [comment]
@derberg Node 18 is being shipped with npm version 9 which generates the package-lock.json version 3.
can our CI/CD handle this or should we go back to node 16/14? 🤔

**Comment by Queen-codes** [comment]
> @Queen-codes thanks, as I see the package-lock.json version 3 is generate which I was not expecting. 🤔
> 
> @derberg Node 18 is being shipped with npm version 9 which generates the package-lock.json version 3. can our CI/CD handle this or should we go back to node 16/14? 🤔

Hi, sorry for the late reply. Is there anything I can do to help?

**Comment by derberg** [comment]
@KhudaDad414 we didn't yet solve the problems of v1 and v2 and you are telling me there is v3 😆

**Comment by KhudaDad414** [comment]
hey @Queen-codes can you use node 16 to regenerate package-lock.json and resolve the conflicts?

**Comment by Queen-codes** [comment]
> hey @Queen-codes can you use node 16 to regenerate package-lock.json and resolve the conflicts?

yeah, sure. thank you

**Comment by KhudaDad414** [comment]
Hi @Queen-codes, do you need some help here?

**Pull request closed without merging**
