### PR TITLE
fix: removes Unused Imports Closes #527

### LINKED ISSUE #527: Remove this unused import of 'MiddlewareCallback'.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_glee&open=AYjh71-PRnF1qFORFvTh&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=asyncapi_glee&open=AYjh71-PRnF1qFORFvTh&tab=code

### PR DESCRIPTION
**Pull request by notpritam**
**Description**
PR aims to remove unused imports of import of 'MiddlewareCallback' from tests/lib/adapter.test.ts directory

**Related issue(s)**
Fixes #527

### CODE REVIEW

**Comment by Souvikns** [comment]
@notpritam we follow [convention commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) that's why the tests are failing, just change the title of the PR accordingly and it should work.

**Comment by notpritam** [comment]
> @notpritam we follow [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) that's why the tests are failing, just change the title of the PR accordingly and it should work.

Done...

**Review by KhudaDad414 — APPROVED** [review]
LGTM!

**Pull request merged**
