### PR TITLE
Addition of AMQP 1.0 adapter

### PR DESCRIPTION
**Pull request by atharvagadkari05**
Created a draft PR #258 
-Added Adapter file for AMQP.
- Unable to install rhea package via NPM
image

### CODE REVIEW

**Comment by fmvilas** [comment]
@atharvagadkari05 do you mind checking your PR? It contains lots of changes that shouldn't be there.

**Comment by KhudaDad414** [comment]
@atharvagadkari05 Hey man, are you still working on this issue? Feel free to reach out if you needed any help :)

**Comment by kaushik-rishi** [comment]
@atharvagadkari05 are you still working on it ?
if not I can pick it up

**Comment by KhudaDad414** [comment]
Closing this PR since the author isn't responsive.

**Pull request closed without merging**
