### PR TITLE
fix: upgrade the package version

### PR DESCRIPTION
**Pull request by SinghiHarsh**
**Description**

-  Upgraded eslint-plugin-sonarjs from  0.5.0 -> 0.18.0  
-  Upgraded typedoc from 0.22.10 -> 0.23.28
**Related issue(s)**

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
hey @SinghiHarsh follow the correct title convention

**Comment by SinghiHarsh** [comment]
> hey @SinghiHarsh follow the correct title convention

Sorry, I'm not aware about it. Could you please share any references to follow ?

**Comment by sambhavgupta0705** [comment]
> > hey @SinghiHarsh follow the correct title convention
> 
> Sorry, I'm not aware about it. Could you please share any references to follow ?

We follow a proper naming convention of Pull requests for better understanding.
You can rename your PR to 'fix: upgrade the package version`

**Comment by KhudaDad414** [comment]
@SinghiHarsh as the bot mentioned we follow conventional commits. you can read more about it here: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by sambhavgupta0705** [comment]
@SinghiHarsh please also update the description and also add the related issue there.

**Review by Souvikns — DISMISSED** [review]

**Comment by pragya-20** [comment]
Hey @KhudaDad414, I tried reproducing the issue but I am not getting the errors while following the below steps:

1. clone glee.
2. run npm i with npm 8 or higher.

**npm version:** 8.15.0.
I can see that Harish's PR has also not been merged yet but I am just getting warnings with no error as of now:
Screenshot from 2023-03-25 23-59-06

**Comment by oviecodes** [comment]
Hey @pragya-20 you're not seeing the errors because the package-lock.json file I'm the glee repo is currently using lockfile version 1. The errors occurred when it was in version 2. Maybe @KhudaDad414 would have to take a look at it.

**Comment by darp99** [comment]
> Hey @KhudaDad414, I tried reproducing the issue but I am not getting the errors while following the below steps:
> 
> 1. clone glee.
> 2. run npm i with npm 8 or higher.
> 
> **npm version:** 8.15.0. I can see that Harish's PR has also not been merged yet but I am just getting warnings with no error as of now: Screenshot from 2023-03-25 23-59-06

Hey @KhudaDad414,  @pragya-20 just little correction I had tried with NPM version 7.20.0 and able to run without any error.

**Comment by KhudaDad414** [comment]
@pragya-20, @oviecodes is right. the current codebase uses lockfile v1. (I don't know why, waited a few minutes for git blame to load but GitHub isn't giving me anything 😆 ).

**Pull request closed without merging**
