### PR TITLE
feat: add AMQP 1.0 support and adapter for Glee

### PR DESCRIPTION
**Pull request by kaushik-rishi**
**Description**
- current decisions
    - use rabbitmq with amqp 1.0 plugin
         - https://www.rabbitmq.com/installing-plugins.html
         - https://www.rabbitmq.com/plugins.html
    - use rhea for amqp 1.0 support

**Related issue(s)**
- #258

### CODE REVIEW

**Comment by kaushik-rishi** [comment]
cc: @KhudaDad414 
Just made a draft PR to show progress.

**Comment by kaushik-rishi** [comment]
I've setup the local AMQP 1.0 broker and fiddling with rhea package to interact with the amqp1.0 local broker

- how I setup the broker
    - run rabbitmq via docker
    - exec into bash shell
    - `rabbitmq-plugins enable rabbitmq_amqp1_0`
- [rhea direct publisher and subscriber](https://gist.github.com/kaushik-rishi/f3b91d8babc56ebbb057f1f0a1b598f7)

I'll further try to understand the events being emitted and how to normalize them to adapt to glee by studying other existing adapters.

**Comment by KhudaDad414** [comment]
> It's about adding a new adapter that supports AMQP 1.0 right? cc: @KhudaDad414 @fmvilas

yes. exactly. in theory it is just a matter of adding a new adapter.

**Comment by KhudaDad414** [comment]
@kaushik-rishi something that I can help with?

**Comment by kaushik-rishi** [comment]
Hey @KhudaDad414.
Was busy for a bit with making proposal and submitting (since the deadline was extended for the project I was submitting to). I'm back on it. Will let you know if I need any. Thanks for understanding. :smile:

**Comment by KhudaDad414** [comment]
@kaushik-rishi are you still working on this?

**Comment by KhudaDad414** [comment]
@kaushik-rishi pingy pongy 😄

**Comment by kaushik-rishi** [comment]
@KhudaDad414 yes, working on this.

**Comment by KhudaDad414** [comment]
Hey @kaushik-rishi do you need some help with this?

**Comment by KhudaDad414** [comment]
hey @kaushik-rishi please reopen this PR when it is ready for review. 🙇

**Pull request closed without merging**
