### PR TITLE
fix: error message on missing auth function

### PR DESCRIPTION
**Pull request by srini047**
**Description**

- Updated the current error message for more clear error debug.

**Related issue(s)**

Fixes: #688

### CODE REVIEW

**Comment by Souvikns** [comment]
The tests are not running for some reason @srini047 can you make a minor change and push it.

**Comment by srini047** [comment]
> The tests are not running for some reason @srini047 can you make a minor change and push it.

@Souvikns I have made minor changes. If still the issue persists, can you let me know. Still wondering why checks are not running.

**Comment by srini047** [comment]
@Souvikns
Can you take a look at it now. I think all the required and generic checks except PR approval checks are passing.

**Review by Souvikns — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
