### PR TITLE
fix: update the docs for glee asyncapi yaml to support v3

### PR DESCRIPTION
**Pull request by afzal442**
**Description**

This PR fixes glee asyncapi yaml to support for v3.

**Related issue(s)**

* Related to #431 
* Part of #480

### CODE REVIEW

**Review by KhudaDad414 — APPROVED** [review]

**Comment by afzal442** [comment]
Hi folks, can anyone approve it so we can see it on website repo?

**Review by Souvikns — APPROVED** [review]

**Pull request merged**
