### PR TITLE
chore(ci): change pages to markdown

### PR DESCRIPTION
**Pull request by Shurtu-gal**
See https://github.com/asyncapi/website/pull/2938

### CODE REVIEW

**Review by KhudaDad414 — APPROVED** [review]
LGTM

**Comment by akshatnema** [comment]
@KhudaDad414 can you please revert this PR? We don't want to merge this before the migration of website is completed.

**Comment by KhudaDad414** [comment]
@akshatnema sure thing. can you open a PR so I can approve it?

@Shurtu-gal For future reference, you can use `/dnm` or `/do-not-merge` command on a PR that you don't want to be merged.

**Comment by Shurtu-gal** [comment]
> @Shurtu-gal For future reference, you can use `/dnm` or `/do-not-merge` command on a PR that you don't want to be merged.

Sure.

Btw, The revert is not needed anymore.

**Comment by akshatnema** [comment]
@KhudaDad414 Yepp, migrated website is live now, so we don't need any revert.

**Pull request merged**
