### PR TITLE
refactor: use different variable name in local scope

### LINKED ISSUE #114: 'server' is already declared in the upper scope.
Details: https://sonarcloud.io/project/issues?id=asyncapi_glee&issues=AXqhLDqqAeRbydshud2H&open=AXqhLDqqAeRbydshud2H

Code: `src/lib/adapter.js`

Explanation: Variables should not be shadowed. Overriding or shadowing a variable declared in an outer scope can strongly impact the readability, and therefore the maintainability, of a piece of code. Further, it could lead maintainers to introduce bugs because they think they’re using one variable but are really using another.

### PR DESCRIPTION
**Pull request by iamsdas**
**Description**
Change variable name as the variable name `server` is already declared in upper scope

**Related issue(s)**
Fixes #114

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@iamsdas Hi! Thanks for contribution! It's not fix, but only refactor - you don't change.fix code, but only make refactor, so please change prefix for PR's title to the `refactor:`

**Comment by iamsdas** [comment]
This was my first contribution in this org yesterday, I had no idea about the nomenclature and just used whatever I found in the first commit I found.

**Comment by magicmatatjahu** [comment]
> This was my first contribution in this org yesterday, I had no idea about the nomenclature and just used whatever I found in the first commit I found.

No worries :)

**Comment by magicmatatjahu** [comment]
@iamsdas We have some problem with macos related workflows, but don't worry I will merge it immediately when all workflows will pass.

**Pull request merged**
